"""create extraction_sessions and simulations tables

Revision ID: 1f8e2f7d543b
Revises: 
Create Date: 2026-03-13 09:33:28.663169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f8e2f7d543b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    sa.Column('layers_ranges', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('antenna_waveform', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_config_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('advanced_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('num_samples_requested', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('sample_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    sa.Column('antenna_kind', sa.Text(), nullable=False),
    sa.Column('antenna_axis', sa.Text(), nullable=False),
    sa.Column('tx_rx_offset_m', sa.Float(), nullable=False),
    sa.Column('resistance', sa.Float(), nullable=True),
    sa.Column('source_start_time', sa.Float(), nullable=True),
    sa.Column('source_end_time', sa.Float(), nullable=True),
    sa.Column('waveform_kind', sa.Text(), nullable=False),
    sa.Column('waveform_amplitude', sa.Float(), nullable=False),
    sa.Column('waveform_center_freq_hz', sa.Float(), nullable=False),
    sa.Column('waveform_name', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('source_height_m', sa.Float(), nullable=False),
    sa.Column('domain_x', sa.Float(), nullable=False),
    sa.Column('domain_y', sa.Float(), nullable=False),
    sa.Column('top_air_extra_m', sa.Float(), nullable=True),
    sa.Column('cells_per_wavelength', sa.Float(), nullable=False),
    sa.Column('max_cell_m', sa.Float(), nullable=False),
    sa.Column('rx_same_height', sa.Boolean(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=False),
    sa.Column('enforce_validity', sa.Boolean(), nullable=False),
    sa.Column('pml_cells', sa.Integer(), nullable=True),
    sa.Column('num_threads', sa.Integer(), nullable=True),
    sa.Column('output_dir', sa.Text(), nullable=True),
    sa.Column('layers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('num_layers', sa.Integer(), nullable=False),
    sa.Column('cylinders', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('boxes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('spheres', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('surface_roughness', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('snapshots', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rx_array', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('signal_ex', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('signal_ey', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('signal_ez', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('signal_hx', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('signal_hy', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('signal_hz', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('signal_length', sa.Integer(), nullable=True),
    sa.Column('simulation_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input_file_path', sa.Text(), nullable=True),
    sa.Column('output_file_path', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    # Indexes for common query patterns
    op.create_index('idx_sessions_user', 'extraction_sessions', ['user_id'])
    op.create_index('idx_sim_session', 'simulations', ['session_id'])
    op.create_index('idx_sim_user', 'simulations', ['user_id'])
    op.create_index('idx_sim_model', 'simulations', ['model'])
    op.create_index('idx_sim_num_layers', 'simulations', ['num_layers'])
    op.create_index('idx_sim_freq', 'simulations', ['waveform_center_freq_hz'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sim_freq', 'simulations')
    op.drop_index('idx_sim_num_layers', 'simulations')
    op.drop_index('idx_sim_model', 'simulations')
    op.drop_index('idx_sim_user', 'simulations')
    op.drop_index('idx_sim_session', 'simulations')
    op.drop_index('idx_sessions_user', 'extraction_sessions')
    op.drop_table('simulations')
    op.drop_table('extraction_sessions')
    # ### end Alembic commands ###
