from .soil_lookup_table import (
    TEXTURE_DEFAULTS,
    THETA_V_BY_TEXTURE_AND_STATE,
    PARTICLE_DENSITY_DEFAULT,
    ORGANIC_FRACTION_BY_LEVEL,
    BULK_DENSITY_PRIOR,
    SALINITY_CLASS_MAP,
    POREWATER_SIGMA_PRIOR,
    ANTENNA_PRESET_TO_FREQ_HZ,
    ANTENNA_PRESET_TO_TXRX_OFFSET_M,
    QUALITY_TO_MESH,
    _texture_bucket,
)
